org: amaan26
app: userreviewsystem
service: userreviewsystem
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - dynamodb:*
        - s3:*
      Resource: "*"

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  login:
    handler: handler.login
    events:
      - httpApi:
          path: /login
          method: post
  register:
    handler: handler.register
    events:
      - httpApi:
          path: /register
          method: post
  updateProfileImage:
    handler: handler.updateProfileImage
    events:
      - httpApi:
          path: /updateProfileImage
          method: post
  getTest:
    handler: handler.getTest
    events:
      - httpApi:
          path: /getTest
          method: get
  answerTest:
    handler: handler.answerTest
    events:
      - httpApi:
          path: /answerTest
          method: post
  addTest:
    handler: handler.addTest
    events:
      - httpApi:
          path: /addTest
          method: post
  listTest:
    handler: handler.listTest
    events:
      - httpApi:
          path: /listTest
          method: get
  listUsers:
    handler: handler.listUsers
    events:
      - httpApi:
          path: /listUsers
          method: get
  addReviewToUser:
    handler: handler.addReviewToUser
    events:
      - httpApi:
          path: /addReviewToUser
          method: post
  

resources:
  Resources:
    profileUploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: profileimagesofuser
    # userTable:
    #   Type: AWS::DynamoDB::Table
    #   Properties:
    #     TableName: users
    #     AttributeDefinitions:
    #       - AttributeName: id
    #         AttributeType: S
    #       - AttributeName: username
    #         AttributeType: S
    #       - AttributeName: password
    #         AttributeType: S
        
    #     KeySchema: 
    #       - AttributeName: id
    #         KeyType: HASH
    #       - AttributeName: username
    #         KeyType: RANGE
    #       - AttributeName: password
    #         KeyType: RANGE
    #     BillingMode: PAY_PER_REQUEST